source "https://rubygems.org"
gem "jekyll", "~> 3.9.0"
gem "minimal-mistakes-jekyll", "~> 4.24"
group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-data"
  gem "jekyll-include-cache"
  gem "jekyll-redirect-from"
  gem "jekyll-relative-links"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
end
